name: Enhancement
description: Suggest an improvement to existing functionality!
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### Read before creating!

        - Avoid creating duplicates! Search through issues and discussions before creating one.
        - Try to make a simple but descriptive title, and explain what the enhancement is.

  - type: textarea
    id: enhancement_description
    attributes:
      label: Enhancement description
      description: Describe what the enhancement is and how it would improve the functionality.
      placeholder: The enhancement would...
    validations:
      required: true

  - type: textarea
    id: current_behavior
    attributes:
      label: Current behavior
      description: Describe how the feature currently works.
      placeholder: Currently, the feature does...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        - Can you implement this yourself?

  - type: textarea
    id: can_you_create
    attributes:
      label: Can you create this yourself?
      description: Answer yes, no, or maybe. If yes, provide details or a PR link.
      placeholder: Yes / No / Maybe
    validations:
      required: false
