name: Enhancement
description: Suggest an improvement to existing functionality!
labels: ["type: enhancement"]
body:
   type markdown
    attributes
      value |
        ### Read before creating!

        - Avoid creating duplicates! Search through issues and discussions before creating one.
        - Try to make a simple but descriptive title, and explain what the enhancement is.

  - type: textarea
    id: current_behavior
    attributes:
      label: Current behavior
      description: Describe how the feature currently works.
      placeholder: Currently, the feature does...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        - Can you create this yourself?

  - type: textarea
    id: current_behavior
    attributes:
    label: 
    description: Answer yes, no, or maybe.
    placeholder: 
  validations:
    required: false
