blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/RedPandaGuy1234/Battleship/discussions
    about: Ask a question, or just discuss about this project on our GitHub Discussions
